image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "9.3"
    - nodejs_version: "11.0.0"
    - nodejs_version: "11.8.0"
    - nodejs_version: "13.0.0"

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - ps: Install-Product node $env:nodejs_version x64
  - npm install --build-from-source
  - scripts/appveyor_build.bat

build: OFF
test: OFF
deploy: OFF
